name: CI with Coverage

on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gcc g++ \
          cmake \
          lcov gcovr \
          libsqlite3-dev
        
    - name: Configure
      run: cmake -S . -B build -DENABLE_COVERAGE=ON
        
    - name: Build
      run: cmake --build build --verbose
        
    - name: Run tests
      working-directory: ./build
      run: ctest --output-on-failure
        
    - name: Generate coverage
      working-directory: ./build
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
        lcov --list coverage.info
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
